# Generated by Django 5.1 on 2024-08-10 16:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostitem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lost',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lost',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='%Y%m%d/'),
        ),
        migrations.AlterField(
            model_name='lost',
            name='lostdate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='lost',
            name='losttime',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='time updated'),
        ),
        migrations.AlterField(
            model_name='lost',
            name='moredesc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
