# Generated by Django 5.1 on 2024-08-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostitem', '0002_alter_lost_description_alter_lost_finished_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lost',
            old_name='finished',
            new_name='founded',
        ),
        migrations.AlterField(
            model_name='lost',
            name='getwhere',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lost',
            name='nowwhere',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
