# Generated by Django 5.1 on 2024-08-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostitem', '0003_rename_finished_lost_founded_alter_lost_getwhere_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lost',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lost',
            name='getwhere',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lost',
            name='nowwhere',
            field=models.TextField(blank=True, null=True),
        ),
    ]
