# Generated by Django 5.1 on 2024-08-17 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0002_alter_category_category_alter_location_location'),
        ('lostitem', '0003_rename_finished_lost_founded_alter_lost_getwhere_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
