# Generated by Django 5.1 on 2024-08-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0006_pointshop_shop_alter_pointshop_stuff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointshop',
            name='shop',
            field=models.TextField(blank=True, null=True),
        ),
    ]
