name: Deploy to EC2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Create the .env file locally
    - name: Create .env file locally
      run: |
        echo "${{ secrets.ENV_VARS }}" > .env

    # Ensure remote directory exists
    - name: Create remote directory
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.KEY }}
        script: mkdir -p /home/ubuntu/srv/ubuntu/clova

    # Copy source files to remote server
    - name: Copy source via rsync
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete
        remote_path: /home/ubuntu/srv/ubuntu/
        remote_host: ${{ secrets.HOST }}
        remote_user: ubuntu
        remote_key: ${{ secrets.KEY }}

    # Copy .env file to remote server using ssh
    - name: Copy .env file using ssh
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.KEY }}
        script: |
          echo "${{ secrets.ENV_VARS }}" > /home/ubuntu/srv/ubuntu/clova/.env

    # Execute deploy script on remote server
    - name: Execute deploy script on remote server
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.KEY }}
        script: sh /home/ubuntu/srv/ubuntu/clova/config/scripts/deploy.sh
